namespace BarbarianSim.Enums;

public enum Aura
{
    WeaponCooldown,
    Vulnerable,
    Slow,
    Immobilize,
    Stun,
    Knockback,
    Knockdown,
    Taunt,
    Fear,
    Tether,
    Daze,
    Chill,
    Freeze,
    Stagger,
    AspectOfTheProtectorCooldown,
    Barrier,
    Whirlwinding,
    Berserking,
    Bleeding,
    ViolentWhirlwind,
    RallyingCry,
    RallyingCryCooldown,
    Unstoppable,
    ChallengingShout,
    ChallengingShoutCooldown,
    WarCry,
    WarCryCooldown,
    IronSkin,
    IronSkinCooldown,
    GutteralYell,
}
